spring:
  application:
    name: aston_notification_service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      topics: user-events-topic
      properties:
        spring.json.type.mapping: userEvent:ru.astondevs.kafka.event.UserEvent
        spring.json.trusted.packages: "ru.astondevs.*"
        auto.offset.reset: earliest

    mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    from: no-reply@example.com
    site-url: https://example.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

logging:
  level:
    ru.astondevs: DEBUG